# Generated by ChatGPT for demo project
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donhang",
            name="dia_chi",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="donhang",
            name="ghi_chu",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="donhang",
            name="ho_ten",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="donhang",
            name="phuong_thuc_tt",
            field=models.CharField(default="COD", max_length=50),
        ),
        migrations.AddField(
            model_name="donhang",
            name="sdt",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="donhang",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("Pending", "Chờ xác nhận"),
                    ("Confirmed", "Đã xác nhận"),
                    ("Cancelled", "Đã huỷ"),
                    ("Approved", "Đã duyệt"),
                    ("Rejected", "Từ chối"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
