# Generated by Django 5.2.12 on 2026-03-07 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_donhang_thong_tin_mua_hang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='trang_thai',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Ngừng kinh doanh')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='nguoi_dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_hangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='phuong_thuc_tt',
            field=models.CharField(choices=[('COD', 'COD (Thanh toán khi nhận hàng)'), ('ChuyenKhoan', 'Chuyển khoản')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='don_hangs', to='shop.sanpham'),
        ),
    ]
