# Generated by Django 5.2.12 on 2026-03-07 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sanpham_trang_thai_alter_donhang_nguoi_dat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='da_hoan_tien',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='phuong_thuc_tt',
            field=models.CharField(choices=[('COD', 'COD (Thanh toán khi nhận hàng)'), ('ChuyenKhoan', 'Chuyển khoản'), ('ViDienTu', 'Ví điện tử')], default='COD', max_length=50),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'Nạp tiền'), ('payment', 'Thanh toán đơn hàng'), ('refund', 'Hoàn tiền')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='shop.donhang')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.wallet')),
            ],
        ),
    ]
