# Generated by Django 6.0.3 on 2026-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_donhang_da_hoan_tien_alter_donhang_phuong_thuc_tt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='loai',
            field=models.CharField(choices=[('dien_thoai', 'Điện thoại'), ('laptop', 'Laptop'), ('phu_kien', 'Phụ kiện'), ('khac', 'Khác')], default='khac', max_length=20),
        ),
    ]
