# Generated by Django 6.0.3 on 2026-03-18 13:36

from django.db import migrations, models


def update_loai_values(apps, schema_editor):
    SanPham = apps.get_model('shop', 'SanPham')
    # Map old values to new default
    mapping = {
        'dien_thoai': 'tien_ich_khac',
        'laptop': 'tien_ich_khac',
        'phu_kien': 'tien_ich_khac',
        'khac': 'tien_ich_khac',
    }
    for old_value, new_value in mapping.items():
        SanPham.objects.filter(loai=old_value).update(loai=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sanpham_loai'),
    ]

    operations = [
        migrations.RunPython(update_loai_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sanpham',
            name='loai',
            field=models.CharField(choices=[('bao_ve', 'Bảo vệ'), ('nang_luong_sac', 'Năng lượng & Sạc'), ('am_thanh', 'Âm thanh'), ('ho_tro_luu_tru', 'Hỗ trợ & Lưu trữ'), ('tien_ich_khac', 'Tiện ích khác')], default='tien_ich_khac', max_length=20),
        ),
    ]
