# Generated by Django 6.0.3 on 2026-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_sanpham_loai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='anh',
            field=models.ImageField(blank=True, default='sanpham/banner.png', null=True, upload_to='sanpham/'),
        ),
    ]
